# Generated by Django 3.1.4 on 2021-05-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('quizid', models.IntegerField(blank=True, null=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nilai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quizid', models.IntegerField()),
                ('answerexplained', models.CharField(blank=True, max_length=512, null=True)),
                ('questiontext', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
